import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {PropsWithChildren} from "react"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zai",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
